import 'dart:convert';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import 'database.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await AppDb.instance.ensureCompany();
  runApp(const OfflineErpApp());
}

class OfflineErpApp extends StatelessWidget {
  const OfflineErpApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false,
    title: 'Offline ERP',
    theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.indigo, brightness: Brightness.light),
    darkTheme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.indigo, brightness: Brightness.dark),
    home: const Shell(),
  );
}

class Shell extends StatefulWidget { const Shell({super.key}); @override State<Shell> createState()=>_ShellState(); }
class _ShellState extends State<Shell> {
  int index=0; final db=AppDb.instance;
  final titles=['Dashboard','Accounting / Ledgers','Inventory','Sales Invoices','Purchase Bills','Vouchers','Banking','Reports','Payroll','GST / Tax','Settings'];
  void refresh(){setState((){});}
  @override Widget build(BuildContext context){
    final pages=[
      DashboardPage(onRefresh:refresh),
      LedgerPage(onRefresh:refresh),
      InventoryPage(onRefresh:refresh),
      SalesPage(onRefresh:refresh),
      PurchasePage(onRefresh:refresh),
      VoucherPage(onRefresh:refresh),
      BankingPage(onRefresh:refresh),
      ReportsPage(),
      PayrollPage(onRefresh:refresh),
      GstPage(onRefresh:refresh),
      SettingsPage(onRefresh:refresh),
    ];
    return Scaffold(
      appBar: AppBar(title: Text(titles[index]), actions:[IconButton(onPressed:()=>showSearch(context:context,delegate:ErpSearchDelegate()),icon:const Icon(Icons.search))]),
      drawer: Drawer(child:SafeArea(child:ListView(padding:EdgeInsets.zero,children:[
        DrawerHeader(decoration:BoxDecoration(color:Theme.of(context).colorScheme.primaryContainer),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(Icons.account_balance,size:42),const SizedBox(height:10),FutureBuilder<List<Map<String,Object?>>>(future:db.query('companies'),builder:(c,s){final n=s.data?.isNotEmpty==true?s.data!.first['name']:'Offline ERP';return Text('$n',style:Theme.of(context).textTheme.titleLarge);}),const Text('Offline-first • SQLite')]),),
        for(int i=0;i<titles.length;i++) ListTile(selected:index==i,leading:Icon(_icons[i]),title:Text(titles[i]),onTap:(){Navigator.pop(context);setState(()=>index=i);}),
      ]))),
      body: IndexedStack(index:index,children:pages),
    );
  }
  static const _icons=[Icons.dashboard,Icons.account_balance_wallet,Icons.inventory_2,Icons.point_of_sale,Icons.shopping_cart,Icons.receipt_long,Icons.account_balance,Icons.analytics,Icons.people,Icons.receipt,Icons.settings];
}

class ErpSearchDelegate extends SearchDelegate<String>{
  @override List<Widget>? buildActions(BuildContext context)=>[IconButton(onPressed:()=>query='',icon:const Icon(Icons.clear))];
  @override Widget? buildLeading(BuildContext context)=>IconButton(onPressed:()=>close(context,''),icon:const Icon(Icons.arrow_back));
  @override Widget buildResults(BuildContext context)=>FutureBuilder<List<Map<String,Object?>>>(future:AppDb.instance.query('ledgers',where:'name LIKE ?',args:['%$query%'],limit:30),builder:(c,s){final rows=s.data??[];return ListView(children:rows.map((r)=>ListTile(title:Text('${r['name']}'),subtitle:Text('Ledger • ${r['gstin']??''}'))).toList());});
  @override Widget buildSuggestions(BuildContext context)=>buildResults(context);
}

String money(Object? n){final v=(n as num?)?.toDouble()??0;return NumberFormat.currency(locale:'en_IN',symbol:'₹',decimalDigits:2).format(v);}
String dateText(Object? v){if(v==null)return '';return DateFormat('dd-MM-yyyy').format(DateTime.tryParse('$v')??DateTime.now());}
Future<String> cid()=>AppDb.instance.ensureCompany();

class DashboardPage extends StatelessWidget{
  final VoidCallback onRefresh; const DashboardPage({super.key,required this.onRefresh});
  @override Widget build(BuildContext context)=>FutureBuilder<Map<String,Object?>>(future:cid().then((id)=>AppDb.instance.summary(id)),builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());final x=s.data??{};return RefreshIndicator(onRefresh:()async{onRefresh();},child:ListView(padding:const EdgeInsets.all(16),children:[
    Text('Business overview',style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:16),
    GridView.count(crossAxisCount:MediaQuery.of(context).size.width>700?4:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.6,children:[
      StatCard('Sales',money(x['sales']),Icons.trending_up),StatCard('Purchases',money(x['purchase']),Icons.shopping_cart),StatCard('Stock Qty',(x['stock']??0).toString(),Icons.inventory_2),StatCard('Customers','${x['customers']??0}',Icons.people),
    ]),const SizedBox(height:20),
    Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Quick actions',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:10),Wrap(spacing:10,runSpacing:10,children:[
      FilledButton.icon(onPressed:()=>_quick(context,'Sales Invoice'),icon:const Icon(Icons.add_shopping_cart),label:const Text('Sales Invoice')),
      OutlinedButton.icon(onPressed:()=>_quick(context,'Purchase Bill'),icon:const Icon(Icons.add_business),label:const Text('Purchase Bill')),
      OutlinedButton.icon(onPressed:()=>_quick(context,'Receipt'),icon:const Icon(Icons.payments),label:const Text('Receipt')),
      OutlinedButton.icon(onPressed:()=>_quick(context,'Payment'),icon:const Icon(Icons.payment),label:const Text('Payment')),
    ])]))),const SizedBox(height:20),
    Card(child:ListTile(leading:const Icon(Icons.offline_bolt),title:const Text('Offline mode'),subtitle:const Text('All business data is stored locally on this phone. Use Settings → Backup before changing phones.'))),
  ]));});
  Future<void> _quick(BuildContext context,String type) async {if(type=='Sales Invoice'){await showDialog(context:context,builder:(_)=>SalesDialog(onSaved:onRefresh));}else if(type=='Purchase Bill'){await showDialog(context:context,builder:(_)=>PurchaseDialog(onSaved:onRefresh));}else{await showDialog(context:context,builder:(_)=>VoucherDialog(kind:type,onSaved:onRefresh));}}
}
class StatCard extends StatelessWidget{final String title,value;final IconData icon;const StatCard(this.title,this.value,this.icon,{super.key});@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Icon(icon),Text(title),Text(value,style:Theme.of(c).textTheme.titleLarge)])));}

class LedgerPage extends StatefulWidget{final VoidCallback onRefresh;const LedgerPage({super.key,required this.onRefresh});@override State<LedgerPage> createState()=>_LedgerPageState();}
class _LedgerPageState extends State<LedgerPage>{String q='';
  @override Widget build(BuildContext context)=>FutureBuilder<List<Map<String,Object?>>>(future:AppDb.instance.query('ledgers',where:q.isEmpty?'1=1':'name LIKE ?',args:q.isEmpty?[]:['%$q%'],orderBy:'name'),builder:(c,s){final rows=s.data??[];return Column(children:[Padding(padding:const EdgeInsets.fromLTRB(16,16,16,8),child:Row(children:[Expanded(child:TextField(decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Search ledgers',border:OutlineInputBorder()),onChanged:(v)=>setState(()=>q=v))),const SizedBox(width:10),FilledButton.icon(onPressed:()=>showDialog(context:context,builder:(_)=>LedgerDialog(onSaved:widget.onRefresh)),icon:const Icon(Icons.add),label:const Text('Ledger'))])),Expanded(child:ListView.builder(itemCount:rows.length,itemBuilder:(c,i){final r=rows[i];return Card(margin:const EdgeInsets.symmetric(horizontal:16,vertical:4),child:ListTile(leading:CircleAvatar(child:Icon(r['is_customer']==1?Icons.person:r['is_supplier']==1?Icons.local_shipping:Icons.account_balance_wallet)),title:Text('${r['name']}'),subtitle:Text('${r['code']??''}  •  ${r['gstin']??'No GSTIN'}'),trailing:Text(money(r['opening_balance']))));}))]);});
}

class LedgerDialog extends StatefulWidget{final VoidCallback onSaved;const LedgerDialog({super.key,required this.onSaved});@override State<LedgerDialog> createState()=>_LedgerDialogState();}
class _LedgerDialogState extends State<LedgerDialog>{final name=TextEditingController(),gst=TextEditingController(),phone=TextEditingController(),opening=TextEditingController();String? group;bool customer=false,supplier=false;List<Map<String,Object?>> groups=[];
  @override void initState(){super.initState();AppDb.instance.query('account_groups',orderBy:'name').then((v){if(mounted)setState((){groups=v;group=v.isNotEmpty?v.first['id'] as String:null;});});}
  @override Widget build(BuildContext c)=>AlertDialog(title:const Text('Create Ledger'),content:SizedBox(width:520,child:SingleChildScrollView(child:Column(children:[field(name,'Ledger name'),DropdownButtonFormField<String>(value:group,items:groups.map((g)=>DropdownMenuItem(value:g['id'] as String,child:Text(g['name'] as String))).toList(),onChanged:(v)=>setState(()=>group=v),decoration:const InputDecoration(labelText:'Group',border:OutlineInputBorder())),field(gst,'GSTIN (optional)'),field(phone,'Phone'),field(opening,'Opening balance',keyboard:TextInputType.number),SwitchListTile(title:const Text('Customer'),value:customer,onChanged:(v)=>setState(()=>customer=v)),SwitchListTile(title:const Text('Supplier'),value:supplier,onChanged:(v)=>setState(()=>supplier=v))])),),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:save,child:const Text('Save'))]);
  Widget field(TextEditingController x,String label,{TextInputType? keyboard})=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:x,keyboardType:keyboard,decoration:InputDecoration(labelText:label,border:const OutlineInputBorder())));
  Future<void> save()async{if(name.text.trim().isEmpty)return;final id=AppDb.instance.id();final company=await cid();await AppDb.instance.insert('ledgers',{'id':id,'company_id':company,'group_id':group,'name':name.text.trim(),'gstin':gst.text.trim(),'phone':phone.text.trim(),'opening_balance':double.tryParse(opening.text)??0,'opening_type':'Dr','is_customer':customer?1:0,'is_supplier':supplier?1:0});await AppDb.instance.audit(company,'ledgers',id,'CREATE',newData:{'name':name.text.trim()});widget.onSaved();if(mounted)Navigator.pop(context);}
}

class InventoryPage extends StatefulWidget{final VoidCallback onRefresh;const InventoryPage({super.key,required this.onRefresh});@override State<InventoryPage> createState()=>_InventoryPageState();}
class _InventoryPageState extends State<InventoryPage>{int tab=0;@override Widget build(BuildContext c)=>Column(children:[TabBarLike(index:tab,onChanged:(v)=>setState(()=>tab=v),labels:const ['Items','Warehouses','Units']),Expanded(child:tab==0?ItemsList(onRefresh:widget.onRefresh):tab==1?SimpleMaster(table:'warehouses',title:'Warehouses',fields:['name','address'],onRefresh:widget.onRefresh):SimpleMaster(table:'units',title:'Units',fields:['name','symbol'],onRefresh:widget.onRefresh))]);}
class TabBarLike extends StatelessWidget{final int index;final ValueChanged<int> onChanged;final List<String> labels;const TabBarLike({super.key,required this.index,required this.onChanged,required this.labels});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(12),child:SegmentedButton<int>(segments:[for(int i=0;i<labels.length;i++)ButtonSegment(value:i,label:Text(labels[i]))],selected:{index},onSelectionChanged:(s)=>onChanged(s.first)));}
class ItemsList extends StatefulWidget{final VoidCallback onRefresh;const ItemsList({super.key,required this.onRefresh});@override State<ItemsList> createState()=>_ItemsListState();}
class _ItemsListState extends State<ItemsList>{@override Widget build(BuildContext c)=>FutureBuilder<List<Map<String,Object?>>>(future:AppDb.instance.query('stock_items',orderBy:'name'),builder:(c,s){final rows=s.data??[];return Column(children:[Align(alignment:Alignment.centerRight,child:Padding(padding:const EdgeInsets.only(right:16,bottom:8),child:FilledButton.icon(onPressed:()=>showDialog(context:context,builder:(_)=>ItemDialog(onSaved:widget.onRefresh)),icon:const Icon(Icons.add),label:const Text('Stock Item')))),Expanded(child:ListView.builder(itemCount:rows.length,itemBuilder:(c,i){final r=rows[i];return Card(margin:const EdgeInsets.symmetric(horizontal:16,vertical:4),child:ListTile(leading:const Icon(Icons.inventory),title:Text('${r['name']}'),subtitle:Text('SKU ${r['sku']??'-'} • HSN ${r['hsn_code']??'-'} • GST ${r['gst_rate']}%'),trailing:Text('${r['opening_qty']}')));}))]);});}
class ItemDialog extends StatefulWidget{final VoidCallback onSaved;const ItemDialog({super.key,required this.onSaved});@override State<ItemDialog> createState()=>_ItemDialogState();}
class _ItemDialogState extends State<ItemDialog>{final name=TextEditingController(),sku=TextEditingController(),hsn=TextEditingController(),gst=TextEditingController(),qty=TextEditingController(),rate=TextEditingController();String? unit,warehouse;
@override Widget build(BuildContext c)=>FutureBuilder<List<Map<String,Object?>>>(future:Future.wait([AppDb.instance.query('units'),AppDb.instance.query('warehouses')]),builder:(c,s){final units=s.data?[0]??[];final wh=s.data?[1]??[];unit??=units.isNotEmpty?units.first['id'] as String:null;warehouse??=wh.isNotEmpty?wh.first['id'] as String:null;return AlertDialog(title:const Text('Stock Item'),content:SizedBox(width:540,child:SingleChildScrollView(child:Column(children:[f(name,'Item name'),f(sku,'SKU'),f(hsn,'HSN/SAC'),f(gst,'GST %',num:true),f(qty,'Opening quantity',num:true),f(rate,'Opening rate',num:true),DropdownButtonFormField<String>(value:unit,items:units.map((x)=>DropdownMenuItem(value:x['id'] as String,child:Text('${x['name']} (${x['symbol']})'))).toList(),onChanged:(v)=>setState(()=>unit=v),decoration:const InputDecoration(labelText:'Unit',border:OutlineInputBorder())),DropdownButtonFormField<String>(value:warehouse,items:wh.map((x)=>DropdownMenuItem(value:x['id'] as String,child:Text(x['name'] as String))).toList(),onChanged:(v)=>setState(()=>warehouse=v),decoration:const InputDecoration(labelText:'Opening warehouse',border:OutlineInputBorder()))]))),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:save,child:const Text('Save'))]);});
Widget f(TextEditingController x,String l,{bool num=false})=>Padding(padding:const EdgeInsets.only(bottom:9),child:TextField(controller:x,keyboardType:num?TextInputType.number:null,decoration:InputDecoration(labelText:l,border:const OutlineInputBorder())));
Future<void> save()async{if(name.text.trim().isEmpty)return;final company=await cid();final id=AppDb.instance.id();await AppDb.instance.insert('stock_items',{'id':id,'company_id':company,'unit_id':unit,'name':name.text.trim(),'sku':sku.text.trim(),'hsn_code':hsn.text.trim(),'gst_rate':double.tryParse(gst.text)??0,'opening_qty':double.tryParse(qty.text)??0,'opening_rate':double.tryParse(rate.text)??0});if(warehouse!=null&&(double.tryParse(qty.text)??0)!=0)await AppDb.instance.insert('stock_movements',{'id':AppDb.instance.id(),'company_id':company,'stock_item_id':id,'warehouse_id':warehouse,'movement_date':DateTime.now().toIso8601String(),'reference_type':'OPENING','reference_id':id,'quantity_in':double.tryParse(qty.text)??0,'rate':double.tryParse(rate.text)??0});widget.onSaved();if(mounted)Navigator.pop(context);}
}

class SalesPage extends StatelessWidget{final VoidCallback onRefresh;const SalesPage({super.key,required this.onRefresh});@override Widget build(BuildContext c)=>TransactionList(table:'sales_invoices',dateField:'invoice_date',numberField:'invoice_no',title:'Sales Invoices',button:'New Sales Invoice',onRefresh:onRefresh,dialogBuilder:()=>SalesDialog(onSaved:onRefresh));}
class PurchasePage extends StatelessWidget{final VoidCallback onRefresh;const PurchasePage({super.key,required this.onRefresh});@override Widget build(BuildContext c)=>TransactionList(table:'purchase_bills',dateField:'bill_date',numberField:'bill_no',title:'Purchase Bills',button:'New Purchase Bill',onRefresh:onRefresh,dialogBuilder:()=>PurchaseDialog(onSaved:onRefresh));}
class TransactionList extends StatelessWidget{final String table,dateField,numberField,title,button;final Widget Function() dialogBuilder;const TransactionList({super.key,required this.table,required this.dateField,required this.numberField,required this.title,required this.button,required this.dialogBuilder});@override Widget build(BuildContext c)=>FutureBuilder<List<Map<String,Object?>>>(future:AppDb.instance.query(table,orderBy:'$dateField DESC'),builder:(c,s){final rows=s.data??[];return Column(children:[Padding(padding:const EdgeInsets.all(16),child:Row(children:[Text(title,style:Theme.of(c).textTheme.titleLarge),const Spacer(),FilledButton.icon(onPressed:()=>showDialog(context:c,builder:(_)=>dialogBuilder()),icon:const Icon(Icons.add),label:Text(button))])),Expanded(child:ListView.builder(itemCount:rows.length,itemBuilder:(c,i){final r=rows[i];return Card(margin:const EdgeInsets.symmetric(horizontal:16,vertical:4),child:ListTile(title:Text('${r[numberField]}'),subtitle:Text(dateText(r[dateField])),trailing:Text(money(r['grand_total']))));}))]);});}

class SalesDialog extends StatefulWidget{final VoidCallback onSaved;const SalesDialog({super.key,required this.onSaved});@override State<SalesDialog> createState()=>_SalesDialogState();}
class _SalesDialogState extends State<SalesDialog>{String? customer,item,warehouse;final qty=TextEditingController(text:'1'),rate=TextEditingController(text:'0'),discount=TextEditingController(text:'0'),gst=TextEditingController(text:'18');bool interstate=false;List<Map<String,Object?>> customers=[],items=[],warehouses=[];
@override Widget build(BuildContext c)=>FutureBuilder<List<List<Map<String,Object?>>>>(future:Future.wait([AppDb.instance.query('ledgers',where:'is_customer=1',orderBy:'name'),AppDb.instance.query('stock_items',orderBy:'name'),AppDb.instance.query('warehouses',orderBy:'name')]),builder:(c,s){if(s.connectionState!=ConnectionState.done)return const AlertDialog(content:SizedBox(height:100,child:Center(child:CircularProgressIndicator())));customers=s.data![0];items=s.data![1];warehouses=s.data![2];customer??=customers.isNotEmpty?customers.first['id'] as String:null;item??=items.isNotEmpty?items.first['id'] as String:null;warehouse??=warehouses.isNotEmpty?warehouses.first['id'] as String:null;return AlertDialog(title:const Text('Sales Invoice'),content:SizedBox(width:580,child:SingleChildScrollView(child:Column(children:[dd('Customer',customer,customers,'name'),dd('Item',item,items,'name'),dd('Warehouse',warehouse,warehouses,'name'),numf(qty,'Quantity'),numf(rate,'Rate'),numf(discount,'Discount %'),numf(gst,'GST %'),SwitchListTile(title:const Text('Inter-state (IGST)'),value:interstate,onChanged:(v)=>setState(()=>interstate=v)),ValueListenableBuilder<TextEditingValue>(valueListenable:qty,builder:(_,__,___)=>_totals())]))),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:save,child:const Text('Post Invoice'))]);});
Widget dd(String label,String? value,List<Map<String,Object?>> rows,String field)=>Padding(padding:const EdgeInsets.only(bottom:9),child:DropdownButtonFormField<String>(value:value,items:rows.map((r)=>DropdownMenuItem(value:r['id'] as String,child:Text('${r[field]}'))).toList(),onChanged:(v){setState((){if(label=='Customer')customer=v;if(label=='Item')item=v;if(label=='Warehouse')warehouse=v;});},decoration:InputDecoration(labelText:label,border:const OutlineInputBorder())));
Widget numf(TextEditingController x,String l)=>Padding(padding:const EdgeInsets.only(bottom:9),child:TextField(controller:x,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:l,border:const OutlineInputBorder()),onChanged:(_)=>setState((){})));
Widget _totals(){final q=double.tryParse(qty.text)??0,r=double.tryParse(rate.text)??0,d=double.tryParse(discount.text)??0,g=double.tryParse(gst.text)??0;final taxable=q*r*(1-d/100),tax=taxable*g/100,total=taxable+tax;return Align(alignment:Alignment.centerRight,child:Text('Taxable ${money(taxable)}   GST ${money(tax)}   Total ${money(total)}',style:const TextStyle(fontWeight:FontWeight.bold)));}
Future<void> save()async{if(customer==null||item==null||warehouse==null)return;final company=await cid();final d=AppDb.instance;final q=double.tryParse(qty.text)??0,r=double.tryParse(rate.text)??0,disc=double.tryParse(discount.text)??0,g=double.tryParse(gst.text)??0;final taxable=q*r*(1-disc/100),tax=taxable*g/100,cgst=interstate?0:tax/2,sgst=interstate?0:tax/2,igst=interstate?tax:0,total=taxable+tax;final invoiceId=d.id();final no=await d.nextVoucherNo(company,'SI');final vType=await _voucherType(company,'SI');await d.transaction((tx)async{final vId=d.id();final sales=await _ledgerId(company,'Sales');final outC=await _ledgerId(company,'Output CGST');final outS=await _ledgerId(company,'Output SGST');final outI=await _ledgerId(company,'Output IGST');await tx.insert('vouchers',{'id':vId,'company_id':company,'voucher_type_id':vType,'voucher_no':no,'voucher_date':DateTime.now().toIso8601String(),'narration':'Sales invoice $no','created_at':DateTime.now().toIso8601String()});await tx.insert('voucher_entries',{'id':d.id(),'voucher_id':vId,'ledger_id':customer,'debit':total,'credit':0});await tx.insert('voucher_entries',{'id':d.id(),'voucher_id':vId,'ledger_id':sales,'debit':0,'credit':taxable});if(cgst>0){await tx.insert('voucher_entries',{'id':d.id(),'voucher_id':vId,'ledger_id':outC,'debit':0,'credit':cgst});await tx.insert('voucher_entries',{'id':d.id(),'voucher_id':vId,'ledger_id':outS,'debit':0,'credit':sgst});}if(igst>0)await tx.insert('voucher_entries',{'id':d.id(),'voucher_id':vId,'ledger_id':outI,'debit':0,'credit':igst});await tx.insert('sales_invoices',{'id':invoiceId,'company_id':company,'voucher_id':vId,'customer_id':customer,'invoice_no':no,'invoice_date':DateTime.now().toIso8601String(),'taxable_amount':taxable,'subtotal':q*r,'discount_amount':q*r*disc/100,'cgst_amount':cgst,'sgst_amount':sgst,'igst_amount':igst,'grand_total':total});await tx.insert('sales_invoice_items',{'id':d.id(),'invoice_id':invoiceId,'stock_item_id':item,'warehouse_id':warehouse,'quantity':q,'rate':r,'discount_percent':disc,'discount_amount':q*r*disc/100,'taxable_amount':taxable,'gst_rate':g,'cgst_amount':cgst,'sgst_amount':sgst,'igst_amount':igst,'total_amount':total});await tx.insert('stock_movements',{'id':d.id(),'company_id':company,'stock_item_id':item,'warehouse_id':warehouse,'movement_date':DateTime.now().toIso8601String(),'reference_type':'SALES','reference_id':invoiceId,'quantity_out':q,'rate':r});});widget.onSaved();if(mounted){Navigator.pop(context);await printInvoice(invoiceId);}}
}

class PurchaseDialog extends StatefulWidget{final VoidCallback onSaved;const PurchaseDialog({super.key,required this.onSaved});@override State<PurchaseDialog> createState()=>_PurchaseDialogState();}
class _PurchaseDialogState extends State<PurchaseDialog>{String? supplier,item,warehouse;final qty=TextEditingController(text:'1'),rate=TextEditingController(text:'0'),discount=TextEditingController(text:'0'),gst=TextEditingController(text:'18');bool interstate=false;List<Map<String,Object?>> suppliers=[],items=[],warehouses=[];
@override Widget build(BuildContext c)=>FutureBuilder<List<List<Map<String,Object?>>>>(future:Future.wait([AppDb.instance.query('ledgers',where:'is_supplier=1',orderBy:'name'),AppDb.instance.query('stock_items',orderBy:'name'),AppDb.instance.query('warehouses',orderBy:'name')]),builder:(c,s){if(s.connectionState!=ConnectionState.done)return const AlertDialog(content:SizedBox(height:100,child:Center(child:CircularProgressIndicator())));suppliers=s.data![0];items=s.data![1];warehouses=s.data![2];supplier??=suppliers.isNotEmpty?suppliers.first['id'] as String:null;item??=items.isNotEmpty?items.first['id'] as String:null;warehouse??=warehouses.isNotEmpty?warehouses.first['id'] as String:null;return AlertDialog(title:const Text('Purchase Bill'),content:SizedBox(width:580,child:SingleChildScrollView(child:Column(children:[dd('Supplier',supplier,suppliers),dd('Item',item,items),dd('Warehouse',warehouse,warehouses),numf(qty,'Quantity'),numf(rate,'Rate'),numf(discount,'Discount %'),numf(gst,'GST %'),SwitchListTile(title:const Text('Inter-state (IGST)'),value:interstate,onChanged:(v)=>setState(()=>interstate=v)),Text('Total ${money(_total())}',style:const TextStyle(fontWeight:FontWeight.bold))]))),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:save,child:const Text('Post Bill'))]);});
Widget dd(String label,String? value,List<Map<String,Object?>> rows)=>Padding(padding:const EdgeInsets.only(bottom:9),child:DropdownButtonFormField<String>(value:value,items:rows.map((r)=>DropdownMenuItem(value:r['id'] as String,child:Text('${r['name']}'))).toList(),onChanged:(v){setState((){if(label=='Supplier')supplier=v;if(label=='Item')item=v;if(label=='Warehouse')warehouse=v;});},decoration:InputDecoration(labelText:label,border:const OutlineInputBorder())));
Widget numf(TextEditingController x,String l)=>Padding(padding:const EdgeInsets.only(bottom:9),child:TextField(controller:x,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:l,border:const OutlineInputBorder()),onChanged:(_)=>setState((){})));
double _total(){final q=double.tryParse(qty.text)??0,r=double.tryParse(rate.text)??0,d=double.tryParse(discount.text)??0,g=double.tryParse(gst.text)??0;final t=q*r*(1-d/100);return t+t*g/100;}
Future<void> save()async{if(supplier==null||item==null||warehouse==null)return;final company=await cid();final d=AppDb.instance;final q=double.tryParse(qty.text)??0,r=double.tryParse(rate.text)??0,disc=double.tryParse(discount.text)??0,g=double.tryParse(gst.text)??0;final taxable=q*r*(1-disc/100),tax=taxable*g/100,cgst=interstate?0:tax/2,sgst=interstate?0:tax/2,igst=interstate?tax:0,total=taxable+tax;final billId=d.id();final no=await d.nextVoucherNo(company,'PB');final vType=await _voucherType(company,'PB');await d.transaction((tx)async{final vId=d.id();final purchase=await _ledgerId(company,'Purchase');final inC=await _ledgerId(company,'Input CGST');final inS=await _ledgerId(company,'Input SGST');final inI=await _ledgerId(company,'Input IGST');await tx.insert('vouchers',{'id':vId,'company_id':company,'voucher_type_id':vType,'voucher_no':no,'voucher_date':DateTime.now().toIso8601String(),'narration':'Purchase bill $no','created_at':DateTime.now().toIso8601String()});await tx.insert('voucher_entries',{'id':d.id(),'voucher_id':vId,'ledger_id':purchase,'debit':taxable,'credit':0});if(cgst>0){await tx.insert('voucher_entries',{'id':d.id(),'voucher_id':vId,'ledger_id':inC,'debit':cgst,'credit':0});await tx.insert('voucher_entries',{'id':d.id(),'voucher_id':vId,'ledger_id':inS,'debit':sgst,'credit':0});}if(igst>0)await tx.insert('voucher_entries',{'id':d.id(),'voucher_id':vId,'ledger_id':inI,'debit':igst,'credit':0});await tx.insert('voucher_entries',{'id':d.id(),'voucher_id':vId,'ledger_id':supplier,'debit':0,'credit':total});await tx.insert('purchase_bills',{'id':billId,'company_id':company,'voucher_id':vId,'supplier_id':supplier,'bill_no':no,'bill_date':DateTime.now().toIso8601String(),'taxable_amount':taxable,'subtotal':q*r,'discount_amount':q*r*disc/100,'cgst_amount':cgst,'sgst_amount':sgst,'igst_amount':igst,'grand_total':total});await tx.insert('purchase_bill_items',{'id':d.id(),'purchase_bill_id':billId,'stock_item_id':item,'warehouse_id':warehouse,'quantity':q,'rate':r,'discount_amount':q*r*disc/100,'taxable_amount':taxable,'gst_rate':g,'cgst_amount':cgst,'sgst_amount':sgst,'igst_amount':igst,'total_amount':total});await tx.insert('stock_movements',{'id':d.id(),'company_id':company,'stock_item_id':item,'warehouse_id':warehouse,'movement_date':DateTime.now().toIso8601String(),'reference_type':'PURCHASE','reference_id':billId,'quantity_in':q,'rate':r});});widget.onSaved();if(mounted)Navigator.pop(context);}
}

class VoucherPage extends StatelessWidget{final VoidCallback onRefresh;const VoucherPage({super.key,required this.onRefresh});@override Widget build(BuildContext c)=>Column(children:[Padding(padding:const EdgeInsets.all(16),child:Wrap(spacing:10,children:[for(final k in ['Receipt','Payment','Contra','Journal'])OutlinedButton.icon(onPressed:()=>showDialog(context:c,builder:(_)=>VoucherDialog(kind:k,onSaved:onRefresh)),icon:const Icon(Icons.add),label:Text(k))])),Expanded(child:FutureBuilder<List<Map<String,Object?>>>(future:AppDb.instance.query('vouchers',orderBy:'voucher_date DESC'),builder:(c,s){final rows=s.data??[];return ListView.builder(itemCount:rows.length,itemBuilder:(c,i)=>Card(margin:const EdgeInsets.symmetric(horizontal:16,vertical:4),child:ListTile(title:Text('${rows[i]['voucher_no']}'),subtitle:Text('${rows[i]['narration']??''} • ${dateText(rows[i]['voucher_date'])}'))));}))]);}
class VoucherDialog extends StatefulWidget{final String kind;final VoidCallback onSaved;const VoucherDialog({super.key,required this.kind,required this.onSaved});@override State<VoucherDialog> createState()=>_VoucherDialogState();}
class _VoucherDialogState extends State<VoucherDialog>{String? debit,credit;final amount=TextEditingController(),narration=TextEditingController();List<Map<String,Object?>> ledgers=[];
@override Widget build(BuildContext c)=>FutureBuilder<List<Map<String,Object?>>>(future:AppDb.instance.query('ledgers',orderBy:'name'),builder:(c,s){ledgers=s.data??[];debit??=ledgers.isNotEmpty?ledgers.first['id'] as String:null;credit??=ledgers.length>1?ledgers[1]['id'] as String:null;return AlertDialog(title:Text(widget.kind),content:SizedBox(width:520,child:Column(mainAxisSize:MainAxisSize.min,children:[dd('Debit',debit,(v)=>setState(()=>debit=v)),dd('Credit',credit,(v)=>setState(()=>credit=v)),TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Amount',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:narration,decoration:const InputDecoration(labelText:'Narration',border:OutlineInputBorder()))])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:save,child:const Text('Post'))]);});
Widget dd(String label,String? value,ValueChanged<String?> f)=>Padding(padding:const EdgeInsets.only(bottom:9),child:DropdownButtonFormField<String>(value:value,items:ledgers.map((r)=>DropdownMenuItem(value:r['id'] as String,child:Text(r['name'] as String))).toList(),onChanged:f,decoration:InputDecoration(labelText:label,border:const OutlineInputBorder())));
Future<void> save()async{final a=double.tryParse(amount.text)??0;if(a<=0||debit==null||credit==null||debit==credit)return;final company=await cid();final d=AppDb.instance;final code={'Receipt':'RC','Payment':'PM','Contra':'CN','Journal':'JV'}[widget.kind]!;final no=await d.nextVoucherNo(company,code);final vType=await _voucherType(company,code);await d.transaction((tx)async{final v=d.id();await tx.insert('vouchers',{'id':v,'company_id':company,'voucher_type_id':vType,'voucher_no':no,'voucher_date':DateTime.now().toIso8601String(),'narration':narration.text,'created_at':DateTime.now().toIso8601String()});await tx.insert('voucher_entries',{'id':d.id(),'voucher_id':v,'ledger_id':debit,'debit':a,'credit':0,'narration':narration.text});await tx.insert('voucher_entries',{'id':d.id(),'voucher_id':v,'ledger_id':credit,'debit':0,'credit':a,'narration':narration.text});});widget.onSaved();if(mounted)Navigator.pop(context);}
}

class BankingPage extends StatelessWidget {
  final VoidCallback onRefresh;
  const BankingPage({super.key, required this.onRefresh});
  @override
  Widget build(BuildContext c) => Column(children: [
    Padding(padding: const EdgeInsets.all(16), child: Row(children: [
      Text('Bank accounts', style: Theme.of(c).textTheme.titleLarge), const Spacer(),
      FilledButton.icon(onPressed: () => showDialog(context: c, builder: (_) => BankDialog(onSaved: onRefresh)), icon: const Icon(Icons.add), label: const Text('Add bank')),
    ])),
    Expanded(child: FutureBuilder<List<Map<String,Object?>>>(future: AppDb.instance.query('bank_accounts', orderBy: 'bank_name'), builder: (c,s) {
      final rows=s.data??[]; return ListView(children: rows.map((r)=>Card(margin:const EdgeInsets.symmetric(horizontal:16,vertical:4),child:ListTile(leading:const Icon(Icons.account_balance),title:Text('${r['bank_name']??'Bank'}'),subtitle:Text('A/C ${r['account_number']??''} • IFSC ${r['ifsc_code']??''}')))).toList());
    }))
  ]);
}
class BankDialog extends StatefulWidget { final VoidCallback onSaved; const BankDialog({super.key,required this.onSaved}); @override State<BankDialog> createState()=>_BankDialogState(); }
class _BankDialogState extends State<BankDialog>{
  final bank=TextEditingController(),account=TextEditingController(),ifsc=TextEditingController(),branch=TextEditingController(); String? ledger; List<Map<String,Object?>> ledgers=[];
  @override Widget build(BuildContext c)=>FutureBuilder<List<Map<String,Object?>>>(future:AppDb.instance.query('ledgers',where:'is_bank=1'),builder:(c,s){ledgers=s.data??[];ledger??=ledgers.isNotEmpty?ledgers.first['id'] as String:null;return AlertDialog(title:const Text('Bank account'),content:SizedBox(width:500,child:Column(mainAxisSize:MainAxisSize.min,children:[f(bank,'Bank name'),f(account,'Account number'),f(ifsc,'IFSC'),f(branch,'Branch'),DropdownButtonFormField<String>(value:ledger,items:ledgers.map((x)=>DropdownMenuItem(value:x['id'] as String,child:Text(x['name'] as String))).toList(),onChanged:(v)=>setState(()=>ledger=v),decoration:const InputDecoration(labelText:'Ledger',border:OutlineInputBorder()))])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:save,child:const Text('Save'))]);});
  Widget f(TextEditingController x,String l)=>Padding(padding:const EdgeInsets.only(bottom:8),child:TextField(controller:x,decoration:InputDecoration(labelText:l,border:const OutlineInputBorder())));
  Future<void> save()async{if(ledger==null)return;final company=await cid();await AppDb.instance.insert('bank_accounts',{'id':AppDb.instance.id(),'company_id':company,'ledger_id':ledger,'bank_name':bank.text,'account_number':account.text,'ifsc_code':ifsc.text,'branch_name':branch.text});widget.onSaved();if(mounted)Navigator.pop(context);}
}

class GstPage extends StatelessWidget { final VoidCallback onRefresh; const GstPage({super.key,required this.onRefresh}); @override Widget build(BuildContext c)=>Column(children:[
  Padding(padding:const EdgeInsets.all(16),child:Row(children:[Text('GST & HSN setup',style:Theme.of(c).textTheme.titleLarge),const Spacer(),FilledButton.icon(onPressed:()=>showDialog(context:c,builder:(_)=>TaxDialog(onSaved:onRefresh)),icon:const Icon(Icons.add),label:const Text('Add GST rate'))])),
  Expanded(child:FutureBuilder<List<Map<String,Object?>>>(future:AppDb.instance.query('tax_rates',orderBy:'gst_rate'),builder:(c,s){final rows=s.data??[];return ListView(children:rows.map((r)=>Card(margin:const EdgeInsets.symmetric(horizontal:16,vertical:4),child:ListTile(leading:const Icon(Icons.percent),title:Text('${r['name']}'),subtitle:Text('CGST ${r['cgst_rate']}% • SGST ${r['sgst_rate']}% • IGST ${r['igst_rate']}%')))).toList());}))
]); }
class TaxDialog extends StatefulWidget { final VoidCallback onSaved; const TaxDialog({super.key,required this.onSaved}); @override State<TaxDialog> createState()=>_TaxDialogState(); }
class _TaxDialogState extends State<TaxDialog>{final name=TextEditingController(),rate=TextEditingController();@override Widget build(BuildContext c)=>AlertDialog(title:const Text('GST rate'),content:Column(mainAxisSize:MainAxisSize.min,children:[f(name,'Name'),f(rate,'GST rate %')]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:save,child:const Text('Save'))]);Widget f(TextEditingController x,String l)=>Padding(padding:const EdgeInsets.only(bottom:8),child:TextField(controller:x,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:l,border:const OutlineInputBorder())));Future<void> save()async{final company=await cid();final r=double.tryParse(rate.text)??0;await AppDb.instance.insert('tax_rates',{'id':AppDb.instance.id(),'company_id':company,'name':name.text.isEmpty?'GST $r%':name.text,'gst_rate':r,'cgst_rate':r/2,'sgst_rate':r/2,'igst_rate':r});widget.onSaved();if(mounted)Navigator.pop(context);}}

class ReportsPage extends StatefulWidget{const ReportsPage({super.key});@override State<ReportsPage> createState()=>_ReportsPageState();}
class _ReportsPageState extends State<ReportsPage>{String report='Day Book';
@override Widget build(BuildContext c)=>Column(children:[Padding(padding:const EdgeInsets.all(16),child:DropdownButtonFormField<String>(value:report,items:const ['Day Book','Ledger Summary','Trial Balance','Profit & Loss','Balance Sheet','Stock Summary','Receivables','Payables'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>report=v!),decoration:const InputDecoration(labelText:'Report',border:OutlineInputBorder()))),Expanded(child:_body())]);
Widget _body()=>FutureBuilder<List<Map<String,Object?>>>(future:_data(),builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());final rows=s.data??[];return ListView(padding:const EdgeInsets.all(16),children:[Text(report,style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:10),if(rows.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(20),child:Text('No data yet.')),),...rows.map((r)=>Card(child:ListTile(title:Text(_title(r)),trailing:Text(_amount(r)))))]);});
String _title(Map<String,Object?> r)=>'${r['name']??r['voucher_no']??r['invoice_no']??r['bill_no']??r['item']??''}';String _amount(Map<String,Object?> r)=>money(r['balance']??r['amount']??r['grand_total']??r['net']??r['qty']);
Future<List<Map<String,Object?>>> _data()async{final d=AppDb.instance;final company=await cid();switch(report){case 'Day Book':return d.query('vouchers',where:'company_id=?',args:[company],orderBy:'voucher_date DESC',limit:200);case 'Ledger Summary':return d.db.then((x)=>x.rawQuery('SELECT l.name, COALESCE(SUM(ve.debit),0)-COALESCE(SUM(ve.credit),0) balance FROM ledgers l LEFT JOIN voucher_entries ve ON ve.ledger_id=l.id WHERE l.company_id=? GROUP BY l.id ORDER BY l.name',[company]));case 'Trial Balance':return d.db.then((x)=>x.rawQuery('SELECT l.name, COALESCE(SUM(ve.debit),0) debit, COALESCE(SUM(ve.credit),0) credit FROM ledgers l LEFT JOIN voucher_entries ve ON ve.ledger_id=l.id WHERE l.company_id=? GROUP BY l.id ORDER BY l.name',[company]));case 'Profit & Loss':return d.db.then((x)=>x.rawQuery("SELECT l.name, CASE WHEN g.nature='INCOME' THEN COALESCE(SUM(ve.credit-ve.debit),0) ELSE COALESCE(SUM(ve.debit-ve.credit),0) END net FROM ledgers l JOIN account_groups g ON g.id=l.group_id LEFT JOIN voucher_entries ve ON ve.ledger_id=l.id WHERE l.company_id=? AND g.nature IN ('INCOME','EXPENSE') GROUP BY l.id ORDER BY l.name",[company]));case 'Balance Sheet':return d.db.then((x)=>x.rawQuery("SELECT l.name, CASE WHEN g.nature='LIABILITY' OR g.nature='EQUITY' THEN COALESCE(SUM(ve.credit-ve.debit),0) ELSE COALESCE(SUM(ve.debit-ve.credit),0) END balance FROM ledgers l JOIN account_groups g ON g.id=l.group_id LEFT JOIN voucher_entries ve ON ve.ledger_id=l.id WHERE l.company_id=? AND g.nature IN ('ASSET','LIABILITY','EQUITY') GROUP BY l.id ORDER BY l.name",[company]));case 'Stock Summary':return d.db.then((x)=>x.rawQuery('SELECT s.name item, COALESCE(SUM(sm.quantity_in-sm.quantity_out),0) qty FROM stock_items s LEFT JOIN stock_movements sm ON sm.stock_item_id=s.id WHERE s.company_id=? GROUP BY s.id ORDER BY s.name',[company]));case 'Receivables':return d.db.then((x)=>x.rawQuery("SELECT l.name, COALESCE(SUM(ve.debit-ve.credit),0) balance FROM ledgers l LEFT JOIN voucher_entries ve ON ve.ledger_id=l.id WHERE l.company_id=? AND l.is_customer=1 GROUP BY l.id HAVING balance<>0 ORDER BY l.name",[company]));case 'Payables':return d.db.then((x)=>x.rawQuery("SELECT l.name, COALESCE(SUM(ve.credit-ve.debit),0) balance FROM ledgers l LEFT JOIN voucher_entries ve ON ve.ledger_id=l.id WHERE l.company_id=? AND l.is_supplier=1 GROUP BY l.id HAVING balance<>0 ORDER BY l.name",[company]));default:return [];}}
}

class PayrollPage extends StatelessWidget{final VoidCallback onRefresh;const PayrollPage({super.key,required this.onRefresh});@override Widget build(BuildContext c)=>Column(children:[Padding(padding:const EdgeInsets.all(16),child:FilledButton.icon(onPressed:()=>showDialog(context:c,builder:(_)=>EmployeeDialog(onSaved:onRefresh)),icon:const Icon(Icons.person_add),label:const Text('Add Employee'))),Expanded(child:FutureBuilder<List<Map<String,Object?>>>(future:AppDb.instance.query('employees',orderBy:'name'),builder:(c,s){final rows=s.data??[];return ListView.builder(itemCount:rows.length,itemBuilder:(c,i)=>Card(margin:const EdgeInsets.symmetric(horizontal:16,vertical:4),child:ListTile(leading:const Icon(Icons.badge),title:Text('${rows[i]['name']}'),subtitle:Text('${rows[i]['designation']??''} • ₹${rows[i]['basic_salary']??0}'))));}))]);}
class EmployeeDialog extends StatefulWidget{final VoidCallback onSaved;const EmployeeDialog({super.key,required this.onSaved});@override State<EmployeeDialog> createState()=>_EmployeeDialogState();}
class _EmployeeDialogState extends State<EmployeeDialog>{final name=TextEditingController(),code=TextEditingController(),designation=TextEditingController(),salary=TextEditingController();@override Widget build(BuildContext c)=>AlertDialog(title:const Text('Employee'),content:Column(mainAxisSize:MainAxisSize.min,children:[f(name,'Name'),f(code,'Employee code'),f(designation,'Designation'),f(salary,'Basic salary',num:true)]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:save,child:const Text('Save'))]);Widget f(TextEditingController x,String l,{bool num=false})=>Padding(padding:const EdgeInsets.only(bottom:8),child:TextField(controller:x,keyboardType:num?TextInputType.number:null,decoration:InputDecoration(labelText:l,border:const OutlineInputBorder())));Future<void> save()async{final company=await cid();await AppDb.instance.insert('employees',{'id':AppDb.instance.id(),'company_id':company,'name':name.text,'employee_code':code.text,'designation':designation.text,'basic_salary':double.tryParse(salary.text)??0,'joining_date':DateTime.now().toIso8601String()});widget.onSaved();if(mounted)Navigator.pop(context);}}

class SettingsPage extends StatelessWidget{final VoidCallback onRefresh;const SettingsPage({super.key,required this.onRefresh});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[
  Card(child:ListTile(leading:const Icon(Icons.business),title:const Text('Company profile'),subtitle:FutureBuilder<List<Map<String,Object?>>>(future:AppDb.instance.query('companies'),builder:(c,s)=>Text(s.data?.isNotEmpty==true?'${s.data!.first['name']} • ${s.data!.first['gstin']??'GSTIN not set'}':'Not configured')),onTap:()=>showDialog(context:c,builder:(_)=>CompanyDialog(onSaved:onRefresh)))),
  Card(child:ListTile(leading:const Icon(Icons.backup),title:const Text('Backup database'),subtitle:const Text('Export all ERP data to a JSON file'),onTap:()=>backup(c))),
  Card(child:ListTile(leading:const Icon(Icons.restore),title:const Text('Restore database'),subtitle:const Text('Replace local data from an ERP JSON backup'),onTap:()=>restore(c))),
  Card(child:ListTile(leading:const Icon(Icons.print),title:const Text('Test invoice printing'),onTap:()=>printInvoice(null))),
  const Card(child:ListTile(leading:Icon(Icons.security),title:Text('Data safety'),subtitle:Text('Use regular backups. The app does not upload your business data to a server.'))),
  const Padding(padding:EdgeInsets.all(12),child:Text('Offline ERP • accounting + inventory + GST-ready documents • v1.0.0')),
]);
Future<void> backup(BuildContext c)async{final json=await AppDb.instance.exportJson();final uri=await FilePicker.saveFile(dialogTitle:'Save ERP backup',fileName:'offline_erp_${DateFormat('yyyyMMdd_HHmm').format(DateTime.now())}.json',bytes:utf8.encode(json));if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(uri==null?'Backup cancelled':'Backup saved')));}
Future<void> restore(BuildContext c)async{final r=await FilePicker.pickFiles(type:FileType.custom,allowedExtensions:['json'],withData:true);if(r==null||r.files.single.bytes==null)return;final ok=await showDialog<bool>(context:c,builder:(_)=>AlertDialog(title:const Text('Restore backup?'),content:const Text('This replaces all current local ERP data. Make a backup first.'),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Restore'))]));if(ok==true){await AppDb.instance.importJson(utf8.decode(r.files.single.bytes!));if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Restore complete. Restart the app if the dashboard still shows old data.')));}}
}

class CompanyDialog extends StatefulWidget{final VoidCallback onSaved;const CompanyDialog({super.key,required this.onSaved});@override State<CompanyDialog> createState()=>_CompanyDialogState();}
class _CompanyDialogState extends State<CompanyDialog>{final name=TextEditingController(),gst=TextEditingController(),pan=TextEditingController(),state=TextEditingController(),address=TextEditingController(),phone=TextEditingController();@override Widget build(BuildContext c)=>FutureBuilder<List<Map<String,Object?>>>(future:AppDb.instance.query('companies'),builder:(c,s){final x=s.data?.isNotEmpty==true?s.data!.first:null;if(x!=null&&name.text.isEmpty){name.text='${x['name']??''}';gst.text='${x['gstin']??''}';pan.text='${x['pan']??''}';state.text='${x['state']??''}';address.text='${x['address']??''}';phone.text='${x['phone']??''}';}return AlertDialog(title:const Text('Company Profile'),content:SizedBox(width:540,child:SingleChildScrollView(child:Column(children:[f(name,'Business name'),f(gst,'GSTIN'),f(pan,'PAN'),f(state,'State'),f(address,'Address',multi:true),f(phone,'Phone')]))),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:save,child:const Text('Save'))]);});Widget f(TextEditingController x,String l,{bool multi=false})=>Padding(padding:const EdgeInsets.only(bottom:9),child:TextField(controller:x,maxLines:multi?3:1,decoration:InputDecoration(labelText:l,border:const OutlineInputBorder())));Future<void> save()async{final company=await cid();await AppDb.instance.update('companies',{'name':name.text,'gstin':gst.text,'pan':pan.text,'state':state.text,'address':address.text,'phone':phone.text},'id=?',[company]);widget.onSaved();if(mounted)Navigator.pop(context);}}

class SimpleMaster extends StatefulWidget {
  final String table, title;
  final List<String> fields;
  final VoidCallback onRefresh;
  const SimpleMaster({super.key, required this.table, required this.title, required this.fields, required this.onRefresh});
  @override State<SimpleMaster> createState() => _SimpleMasterState();
}

class _SimpleMasterState extends State<SimpleMaster> {
  @override
  Widget build(BuildContext c) {
    return Column(children: [
      Align(
        alignment: Alignment.centerRight,
        child: Padding(
          padding: const EdgeInsets.only(right: 16, bottom: 8),
          child: FilledButton.icon(
            onPressed: () => showDialog(context: c, builder: (_) => SimpleDialogForm(table: widget.table, title: widget.title, fields: widget.fields, onSaved: widget.onRefresh)),
            icon: const Icon(Icons.add), label: Text(widget.title),
          ),
        ),
      ),
      Expanded(
        child: FutureBuilder<List<Map<String, Object?>>>(
          future: AppDb.instance.query(widget.table, orderBy: 'name'),
          builder: (c, s) {
            final rows = s.data ?? [];
            return ListView(
              children: rows.map((r) => Card(
                margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
                child: ListTile(
                  title: Text('${r['name']}'),
                  subtitle: Text(widget.fields.skip(1).map((f) => '${r[f] ?? ''}').join(' • ')),
                ),
              )).toList(),
            );
          },
        ),
      ),
    ]);
  }
}

class SimpleDialogForm extends StatefulWidget{final String table,title;final List<String> fields;final VoidCallback onSaved;const SimpleDialogForm({super.key,required this.table,required this.title,required this.fields,required this.onSaved});@override State<SimpleDialogForm> createState()=>_SimpleDialogFormState();}
class _SimpleDialogFormState extends State<SimpleDialogForm>{late final Map<String,TextEditingController> ctrls={for(final f in widget.fields)f:TextEditingController()};@override Widget build(BuildContext c)=>AlertDialog(title:Text('Add ${widget.title}'),content:Column(mainAxisSize:MainAxisSize.min,children:widget.fields.map((f)=>Padding(padding:const EdgeInsets.only(bottom:8),child:TextField(controller:ctrls[f],decoration:InputDecoration(labelText:f,border:const OutlineInputBorder())))).toList()),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:save,child:const Text('Save'))]);Future<void> save()async{final company=await cid();final data=<String,Object?>{'id':AppDb.instance.id(),'company_id':company};for(final f in widget.fields)data[f]=ctrls[f]!.text;await AppDb.instance.insert(widget.table,data);widget.onSaved();if(mounted)Navigator.pop(context);}}

class PurchaseDialogPlaceholder extends StatelessWidget{const PurchaseDialogPlaceholder({super.key});@override Widget build(BuildContext c)=>const SizedBox();}

Future<String> _ledgerId(String company,String name)async{final r=await AppDb.instance.query('ledgers',where:'company_id=? AND name=?',args:[company,name],limit:1);if(r.isEmpty)throw Exception('Ledger missing: $name');return r.first['id'] as String;}
Future<String> _voucherType(String company,String code)async{final r=await AppDb.instance.query('voucher_types',where:'company_id=? AND code=?',args:[company,code],limit:1);if(r.isEmpty)throw Exception('Voucher type missing: $code');return r.first['id'] as String;}

Future<void> printInvoice(String? invoiceId)async{
  final d=AppDb.instance;final doc=pw.Document();String title='Offline ERP';String body='';
  if(invoiceId!=null){final inv=(await d.query('sales_invoices',where:'id=?',args:[invoiceId],limit:1)).first;final customer=(await d.query('ledgers',where:'id=?',args:[inv['customer_id']],limit:1)).first;final items=await d.query('sales_invoice_items',where:'invoice_id=?',args:[invoiceId]);title='Tax Invoice ${inv['invoice_no']}';body='Customer: ${customer['name']}\nDate: ${dateText(inv['invoice_date'])}\n\n';for(final i in items){final item=(await d.query('stock_items',where:'id=?',args:[i['stock_item_id']],limit:1)).first;body+='${item['name']}  Qty ${i['quantity']} × ${money(i['rate'])} = ${money(i['total_amount'])}\n';}body+='\nTaxable: ${money(inv['taxable_amount'])}\nCGST: ${money(inv['cgst_amount'])}\nSGST: ${money(inv['sgst_amount'])}\nIGST: ${money(inv['igst_amount'])}\nTOTAL: ${money(inv['grand_total'])}';}else{body='PDF printing test\nYour invoice/report printer is connected to the app.';}
  doc.addPage(pw.MultiPage(build:(ctx)=>[pw.Header(level:0,child:pw.Text(title)),pw.Paragraph(text:body)]));await Printing.layoutPdf(onLayout:(format)async=>doc.save());
}
